spring.application.name=gestionprojet

### config of DB
spring.datasource.url=jdbc:postgresql://localhost:5432/gestionprojet
spring.datasource.username=postgres
spring.datasource.password=sousou
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080


spring.mail.host: sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=25c0817bee4a67
spring.mail.password=41b63e6760aa52
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true